### ISSUE TITLE
USER STORY: Edit a comment

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project5#23]
**EPIC**: Recipes Management

 As an **owner of a comment** I can **edit my comment** so that **I can fix or update my existing comment**

**Acceptance Criteria**:

**Tasks**:
- [x] Add the currentUser hook to the Comment component
- [x] import MoreDropdown component into it
- [x] Create CommentEditForm  component
- [x] Add handleEdit functionality 
- [x] import it in Comment component with appropriate props
