### ISSUE TITLE
USER STORY: Follow/Unfollow a user

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project5#27]
**EPIC**: Profile Management

As a **logged in user** I can **follow and unfollow other users** so that **I can see and remove posts by specific users in my posts feed**

**Acceptance Criteria**:

**Tasks**:

- [x] create follow/ unfollow buttons and create their oclick handle event
- [x] create API request to followers instance
- [x] destructure handle follow/unfollow in ProfilePage component and Profile component
