### ISSUE TITLE
USER STORY: Edit profile

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project5#29]
**EPIC**: Profile Management

As a **logged in user** I can **edit my profile** so that **I can change my profile picture and bio**

**Acceptance Criteria**:

- users should be able to see three dots ico in their own profilepage with a drop down menu that containg edit profile option
- after clicking on this option, users should be redirect to the profile edit frorm so can add new information in Bio , img  and save it

**Tasks**:

- [x] Add and export the ProfileEditDropdown component in MoreDropdown component
- [x] import it in ProfilePage.js
- [x] Add profileEditFprm.js files to profiles directory and implement it 
- [x] wire it the relevant routes in App.js
